<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#07101f">
    <meta name="robots" content="noindex, nofollow">
    <title>AutoMind Admin — Operations Center</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
@php
    $initials = fn (?string $name) => collect(preg_split('/\s+/', trim($name ?: 'Unknown')))->filter()->take(2)->map(fn ($part) => mb_strtoupper(mb_substr($part, 0, 1)))->implode('');
    $statusTone = fn (?string $status) => match (true) {
        in_array($status, ['active', 'completed', 'confirmed', 'processed', 'sent', 'verified', 'healthy'], true) => 'success',
        in_array($status, ['failed', 'cancelled', 'suspended', 'deleted', 'rejected', 'critical'], true) => 'danger',
        in_array($status, ['requested', 'queued', 'analyzing', 'uploading', 'pending', 'received', 'gracePeriod', 'billingRetry'], true) => 'warning',
        default => 'neutral',
    };
    $maxWeekly = max(1, (int) $weeklyDiagnostics->max('count'));
@endphp
<body class="admin-page admin-v2" data-initial-view="{{ session('admin_view', 'overview') }}">
    <aside class="admin-sidebar" data-admin-sidebar>
        <div class="sidebar-brand-wrap">
            <a class="brand" href="{{ route('admin.dashboard') }}" aria-label="AutoMind admin home">
                <span class="brand-mark"><img src="{{ asset('images/automind-logo.png') }}" alt=""></span>
                <span class="brand-name">AUTO<span>MIND</span></span>
            </a>
            <button class="sidebar-close" type="button" aria-label="Close menu" data-sidebar-close>×</button>
        </div>
        <div class="workspace-chip"><span class="workspace-avatar">AM</span><div><strong>AutoMind HQ</strong><small>{{ ucfirst(app()->environment()) }} workspace</small></div><span class="workspace-caret">⌄</span></div>
        <nav class="admin-nav" aria-label="Admin navigation">
            <span class="nav-label">Workspace</span>
            <a class="admin-nav-item active" href="#overview" data-admin-view="overview"><i>⌂</i><span>Overview</span></a>
            <a class="admin-nav-item" href="#users" data-admin-view="users"><i>♙</i><span>Users</span><b>{{ $overview['suspendedUsers'] }}</b></a>
            <a class="admin-nav-item" href="#vehicles" data-admin-view="vehicles"><i>◇</i><span>Vehicles</span></a>
            <a class="admin-nav-item" href="#diagnostics" data-admin-view="diagnostics"><i>◎</i><span>Diagnostics</span><b>{{ $overview['failedAiRuns'] }}</b></a>
            <a class="admin-nav-item" href="#mechanics" data-admin-view="mechanics"><i>⌘</i><span>Mechanics</span></a>
            <a class="admin-nav-item" href="#appointments" data-admin-view="appointments"><i>▦</i><span>Appointments</span><b>{{ $overview['pendingAppointments'] }}</b></a>
            <a class="admin-nav-item" href="#billing" data-admin-view="billing"><i>¤</i><span>Billing</span><b>{{ $billingOverview['eventsNeedingAttention'] }}</b></a>
            <span class="nav-label">Operations</span>
            <a class="admin-nav-item" href="#ai" data-admin-view="ai"><i>✦</i><span>AI operations</span></a>
            <a class="admin-nav-item" href="#notifications" data-admin-view="notifications"><i>♢</i><span>Notifications</span></a>
            <a class="admin-nav-item" href="#catalog" data-admin-view="catalog"><i>▤</i><span>Catalog & rates</span></a>
            <a class="admin-nav-item" href="#settings" data-admin-view="settings"><i>⚙</i><span>Settings</span></a>
            <a class="admin-nav-item" href="#audit" data-admin-view="audit"><i>≋</i><span>Audit trail</span></a>
        </nav>
        <div class="sidebar-status"><div><span><i></i> Dashboard connected</span><small>Live application data</small></div><b>{{ number_format($overview['aiSuccessRate'], 1) }}%</b></div>
        <div class="sidebar-user">
            <span class="user-avatar">{{ $initials(session('automind_admin_username', 'admin')) }}</span>
            <div><strong>{{ session('automind_admin_username', 'admin') }}</strong><small>Super administrator</small></div>
            <form method="POST" action="{{ route('admin.logout') }}">@csrf<button type="submit" aria-label="Sign out" title="Sign out">↪</button></form>
        </div>
    </aside>

    <div class="admin-shell">
        <header class="admin-topbar">
            <div class="topbar-left">
                <button class="sidebar-open" type="button" aria-label="Open menu" data-sidebar-open>☰</button>
                <div class="breadcrumbs"><span>AutoMind</span><i>/</i><strong data-current-view>Overview</strong></div>
            </div>
            <div class="topbar-actions">
                <label class="admin-search"><span>⌕</span><input type="search" placeholder="Search the current view…" aria-label="Search current dashboard view" data-global-search><kbd>⌘ K</kbd></label>
                <button class="preview-site-button" type="button" data-export-current>Export CSV <span>⇩</span></button>
                <a class="icon-button" href="{{ route('landing') }}" target="_blank" aria-label="Open public website" title="Open public website">↗</a>
            </div>
        </header>

        <main class="admin-content">
            @unless ($databaseControlsAvailable && $accountStatusAvailable)
                <div class="admin-alert warning"><span>!</span><div><strong>Database upgrade required</strong><small>The dashboard is running in compatibility mode. Apply pending migrations to enable account status and platform controls.</small></div></div>
            @endunless
            @if (filled(data_get($platformSettings, 'maintenance_banner.value')))
                <div class="admin-alert warning"><span>i</span><div><strong>Maintenance notice</strong><small>{{ data_get($platformSettings, 'maintenance_banner.value') }}</small></div></div>
            @endif
            @if (session('admin_status'))
                <div class="admin-alert success" data-flash-alert><span>✓</span><div><strong>{{ session('admin_status') }}</strong><small>The dashboard has refreshed with the latest data.</small></div><button type="button" aria-label="Dismiss">×</button></div>
            @endif
            @if ($errors->any())
                <div class="admin-alert error" data-flash-alert><span>!</span><div><strong>That change could not be saved.</strong><small>{{ $errors->first() }}</small></div><button type="button" aria-label="Dismiss">×</button></div>
            @endif

            <section class="admin-view active" data-view="overview">
                <div class="admin-heading">
                    <div><span class="admin-eyebrow"><i></i> LIVE OPERATIONS</span><h1>Command center</h1><p>Real-time visibility across customers, diagnostics, workshops, revenue, and AI delivery.</p></div>
                    <div class="heading-actions"><span class="environment-pill"><i></i>{{ strtoupper(app()->environment()) }}</span><button class="admin-button primary" type="button" data-admin-view="users">Manage users <span>→</span></button></div>
                </div>
                <div class="metric-grid">
                    <article class="metric-card"><div class="metric-top"><span class="metric-icon blue">♙</span><span class="metric-trend">{{ number_format($overview['activeUsers']) }} active</span></div><small>Total users</small><strong>{{ number_format($overview['users']) }}</strong><p><i style="--bar:{{ $overview['users'] ? min(100, ($overview['activeUsers'] / $overview['users']) * 100) : 0 }}%"></i></p><span>Signed in during the last 7 days</span></article>
                    <article class="metric-card"><div class="metric-top"><span class="metric-icon cyan">◎</span><span class="metric-trend">+{{ number_format($overview['diagnosticsToday']) }} today</span></div><small>Diagnostics</small><strong>{{ number_format($overview['diagnostics']) }}</strong><p><i style="--bar:76%"></i></p><span>Across {{ number_format($overview['vehicles']) }} registered vehicles</span></article>
                    <article class="metric-card"><div class="metric-top"><span class="metric-icon purple">✦</span><span class="metric-trend {{ $overview['aiSuccessRate'] >= 95 ? 'up' : '' }}">7-day quality</span></div><small>AI success rate</small><strong>{{ number_format($overview['aiSuccessRate'], 1) }}%</strong><p><i style="--bar:{{ $overview['aiSuccessRate'] }}%"></i></p><span>{{ number_format($overview['failedAiRuns']) }} failed runs need attention</span></article>
                    <article class="metric-card"><div class="metric-top"><span class="metric-icon amber">⌘</span><span class="metric-trend">{{ number_format($overview['pendingAppointments']) }} open</span></div><small>Verified mechanics</small><strong>{{ number_format($overview['verifiedMechanics']) }}</strong><p><i style="--bar:82%"></i></p><span>Requested and confirmed bookings</span></article>
                </div>
                <div class="dashboard-grid v2-grid">
                    <article class="admin-panel performance-panel">
                        <div class="panel-title"><div><strong>Diagnostic activity</strong><span>New sessions during the last seven days</span></div><span class="live-label"><i></i>Live data</span></div>
                        <div class="chart-summary"><strong>{{ number_format($weeklyDiagnostics->sum('count')) }}</strong><small>Total sessions this week</small></div>
                        <div class="line-chart bar-chart" aria-label="Diagnostic activity for the last seven days">
                            <div class="chart-lines"><i></i><i></i><i></i><i></i></div>
                            <div class="chart-bars">
                                @forelse ($weeklyDiagnostics as $day)<span style="--h:{{ max(4, ($day['count'] / $maxWeekly) * 100) }}%" title="{{ $day['label'] }}: {{ $day['count'] }}"><i></i><b>{{ $day['count'] }}</b></span>@empty
                                    @foreach (range(1, 7) as $empty)<span style="--h:4%"><i></i><b>0</b></span>@endforeach
                                @endforelse
                            </div>
                            <div class="chart-labels">@forelse ($weeklyDiagnostics as $day)<span>{{ strtoupper($day['label']) }}</span>@empty @foreach (['MON','TUE','WED','THU','FRI','SAT','SUN'] as $day)<span>{{ $day }}</span>@endforeach @endforelse</div>
                        </div>
                    </article>
                    <article class="admin-panel health-panel">
                        <div class="panel-title"><div><strong>Operations pulse</strong><span>Items requiring attention</span></div><span class="healthy-pill {{ $overview['failedAiRuns'] ? 'attention' : '' }}"><i></i>{{ $overview['failedAiRuns'] ? 'Review' : 'Healthy' }}</span></div>
                        <div class="ops-list">
                            <button type="button" data-admin-view="ai"><span class="ops-icon {{ $overview['failedAiRuns'] ? 'red' : 'green' }}">✦</span><span><strong>{{ number_format($overview['failedAiRuns']) }} failed AI runs</strong><small>Inspect errors and retry eligible work</small></span><b>→</b></button>
                            <button type="button" data-admin-view="users"><span class="ops-icon amber">♙</span><span><strong>{{ number_format($overview['suspendedUsers']) }} suspended users</strong><small>Review account access and reasons</small></span><b>→</b></button>
                            <button type="button" data-admin-view="billing"><span class="ops-icon {{ $billingOverview['eventsNeedingAttention'] ? 'red' : 'green' }}">¤</span><span><strong>{{ number_format($billingOverview['eventsNeedingAttention']) }} billing events</strong><small>Pending, failed, or unprocessed events</small></span><b>→</b></button>
                        </div>
                    </article>
                    <article class="admin-panel recent-panel">
                        <div class="panel-title"><div><strong>Recent diagnostics</strong><span>The latest customer analysis sessions</span></div><button class="panel-link" type="button" data-admin-view="diagnostics">View all →</button></div>
                        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Driver</th><th>Vehicle</th><th>Report</th><th>Progress</th><th>Status</th><th>Created</th></tr></thead><tbody>
                            @forelse ($diagnostics->take(6) as $diagnosis)
                                <tr><td><span class="table-person">{{ $initials($diagnosis->user?->name) }}</span><strong>{{ $diagnosis->user?->name ?? 'Deleted user' }}</strong></td><td><strong>{{ $diagnosis->vehicle?->brand }} {{ $diagnosis->vehicle?->model }}</strong><small>{{ $diagnosis->vehicle?->year }} · {{ number_format($diagnosis->vehicle?->mileage_km ?? 0) }} km</small></td><td>{{ $diagnosis->report?->translations?->firstWhere('locale', 'en')?->title ?? 'Not generated' }}</td><td><b>{{ $diagnosis->progress_percentage }}%</b></td><td><span class="status-pill {{ $statusTone($diagnosis->status) }}">{{ $diagnosis->status }}</span></td><td>{{ $diagnosis->created_at?->diffForHumans() }}</td></tr>
                            @empty <tr><td colspan="6"><div class="empty-state">No diagnostic sessions yet.</div></td></tr> @endforelse
                        </tbody></table></div>
                    </article>
                </div>
            </section>

            <section class="admin-view" data-view="users">
                <x-admin-heading title="Users" eyebrow="CUSTOMER ACCESS" description="Manage profiles, permissions, account access, and deleted accounts." />
                <div class="resource-stats">
                    <article><span class="metric-icon blue">♙</span><div><small>All accounts</small><strong>{{ number_format($users->count()) }} shown</strong></div></article>
                    <article><span class="metric-icon cyan">✓</span><div><small>Active this week</small><strong>{{ number_format($overview['activeUsers']) }}</strong></div></article>
                    <article><span class="metric-icon amber">!</span><div><small>Suspended</small><strong>{{ number_format($overview['suspendedUsers']) }}</strong></div></article>
                    <article><span class="metric-icon purple">◇</span><div><small>Administrators</small><strong>{{ number_format($users->where('is_admin', true)->count()) }}</strong></div></article>
                </div>
                <article class="admin-panel resource-table-panel">
                    <div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search name, email, phone, or city…" data-table-search="users-table"></label><div class="toolbar-note">Latest 50 including deleted accounts</div></div>
                    <div class="admin-table-wrap"><table class="admin-table resource-table" id="users-table" data-export-name="users"><thead><tr><th>User</th><th>Contact</th><th>Activity</th><th>Role</th><th>Last login</th><th>Status</th><th></th></tr></thead><tbody>
                        @forelse ($users as $user)
                            @php $userState = $user->trashed() ? 'deleted' : ($user->suspended_at ? 'suspended' : 'active'); @endphp
                            <tr><td><span class="table-person">{{ $initials($user->name) }}</span><span><strong>{{ $user->name }}</strong><small>{{ $user->id }}</small></span></td><td><strong>{{ $user->email }}</strong><small>{{ $user->phone ?: ($user->city ?: 'No phone or city') }}</small></td><td><strong>{{ $user->vehicles_count }} vehicles · {{ $user->diagnostics_count }} diagnostics</strong><small>{{ $user->appointments_count }} appointments</small></td><td>{{ $user->is_admin ? ($user->admin_role ?: 'SUPER_ADMIN') : 'Customer' }}</td><td>{{ $user->last_login_at?->diffForHumans() ?? 'Never' }}</td><td><span class="status-pill {{ $statusTone($userState) }}">{{ $userState }}</span></td><td class="row-actions">
                                @if ($user->trashed())<form method="POST" action="{{ route('admin.users.restore', $user->id) }}">@csrf<button class="table-action" type="submit">Restore</button></form>
                                @else<button class="table-action" type="button" data-open-dialog="user-{{ $user->id }}">Manage</button>@endif
                            </td></tr>
                        @empty <tr><td colspan="7"><div class="empty-state">No users found.</div></td></tr> @endforelse
                    </tbody></table></div>
                </article>
                @foreach ($users->whereNull('deleted_at') as $user)
                    <dialog class="admin-dialog" id="user-{{ $user->id }}"><div class="dialog-head"><div><span>User access</span><h2>{{ $user->name }}</h2><p>{{ $user->email }}</p></div><button type="button" data-close-dialog aria-label="Close">×</button></div>
                        <form method="POST" action="{{ route('admin.users.update', $user) }}" class="dialog-form">@csrf @method('PATCH')
                            <div class="form-grid"><label><span>Name</span><input name="name" value="{{ $user->name }}" required></label><label><span>Email</span><input name="email" type="email" value="{{ $user->email }}" required></label><label><span>Phone</span><input name="phone" value="{{ $user->phone }}"></label><label><span>City</span><input name="city" value="{{ $user->city }}"></label><label><span>Country</span><input name="country_code" value="{{ $user->country_code }}" maxlength="2"></label><label><span>Currency</span><input name="currency" value="{{ $user->currency }}" maxlength="3" required></label><label><span>Language</span><select name="locale"><option value="en" @selected($user->locale === 'en')>English</option><option value="ar" @selected($user->locale === 'ar')>Arabic</option></select></label><label><span>Access role</span><select name="admin_role"><option value="">Customer</option>@foreach (['SUPER_ADMIN','BILLING_ADMIN','SUPPORT_AGENT','ANALYST','AUDITOR'] as $role)<option value="{{ $role }}" @selected($user->admin_role === $role)>{{ str_replace('_', ' ', $role) }}</option>@endforeach</select></label></div>
                            <input type="hidden" name="is_admin" value="0"><label class="check-row"><input type="checkbox" name="is_admin" value="1" @checked($user->is_admin)><span><strong>API administrator</strong><small>Allows access to protected admin API endpoints.</small></span></label>
                            <div class="dialog-actions"><button type="button" class="admin-button secondary" data-close-dialog>Cancel</button><button class="admin-button primary" type="submit">Save user</button></div>
                        </form>
                        @if ($accountStatusAvailable)<div class="danger-zone"><div><strong>{{ $user->suspended_at ? 'Reactivate account' : 'Suspend account' }}</strong><p>{{ $user->suspended_at ? $user->suspension_reason : 'Immediately revokes active API and push-device sessions.' }}</p></div><form method="POST" action="{{ route('admin.users.suspension', $user) }}">@csrf<input type="hidden" name="suspended" value="{{ $user->suspended_at ? 0 : 1 }}">@unless($user->suspended_at)<input name="reason" placeholder="Reason for suspension" required>@endunless<button type="submit" class="admin-button {{ $user->suspended_at ? 'secondary' : 'danger' }}" data-confirm="{{ $user->suspended_at ? 'Reactivate this user?' : 'Suspend this user and revoke all active sessions?' }}">{{ $user->suspended_at ? 'Reactivate' : 'Suspend' }}</button></form></div>@endif
                        <div class="danger-zone"><div><strong>Delete account</strong><p>Soft-deletes the user. Their account can be restored from this dashboard.</p></div><form method="POST" action="{{ route('admin.users.destroy', $user) }}">@csrf @method('DELETE')<button type="submit" class="admin-button danger" data-confirm="Move this user to deleted accounts?">Delete account</button></form></div>
                    </dialog>
                @endforeach
            </section>

            <section class="admin-view" data-view="vehicles">
                <x-admin-heading title="Vehicles" eyebrow="FLEET DATA" description="Review ownership, mileage, health, and diagnostic history." />
                <div class="resource-stats"><article><span class="metric-icon blue">◇</span><div><small>Registered</small><strong>{{ number_format($overview['vehicles']) }}</strong></div></article><article><span class="metric-icon cyan">✓</span><div><small>Healthy 80+</small><strong>{{ number_format($vehicles->where('health_score', '>=', 80)->count()) }}</strong></div></article><article><span class="metric-icon amber">!</span><div><small>Needs attention</small><strong>{{ number_format($vehicles->where('health_score', '<', 60)->count()) }}</strong></div></article><article><span class="metric-icon purple">◎</span><div><small>Diagnostics shown</small><strong>{{ number_format($vehicles->sum('diagnostics_count')) }}</strong></div></article></div>
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search vehicle, owner, VIN, or plate…" data-table-search="vehicles-table"></label><div class="toolbar-note">Latest 50 vehicles</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="vehicles-table" data-export-name="vehicles"><thead><tr><th>Vehicle</th><th>Owner</th><th>Mileage</th><th>Health</th><th>Diagnostics</th><th>Updated</th><th></th></tr></thead><tbody>
                    @forelse ($vehicles as $vehicle)<tr><td><strong>{{ $vehicle->brand }} {{ $vehicle->model }}</strong><small>{{ $vehicle->year }} · {{ $vehicle->nickname ?: ($vehicle->plate_number ?: 'No nickname') }}</small></td><td><strong>{{ $vehicle->user?->name ?? 'Deleted user' }}</strong><small>{{ $vehicle->user?->email }}</small></td><td>{{ number_format($vehicle->mileage_km) }} km</td><td><span class="health-value"><i style="--health:{{ $vehicle->health_score }}%"></i></span><b>{{ $vehicle->health_score }}%</b></td><td>{{ $vehicle->diagnostics_count }}</td><td>{{ $vehicle->updated_at?->diffForHumans() }}</td><td><button class="table-action" type="button" data-open-dialog="vehicle-{{ $vehicle->id }}">Manage</button></td></tr>
                    @empty <tr><td colspan="7"><div class="empty-state">No vehicles found.</div></td></tr> @endforelse
                </tbody></table></div></article>
                @foreach ($vehicles->whereNull('deleted_at') as $vehicle)<dialog class="admin-dialog" id="vehicle-{{ $vehicle->id }}"><div class="dialog-head"><div><span>Vehicle record</span><h2>{{ $vehicle->brand }} {{ $vehicle->model }}</h2><p>{{ $vehicle->user?->name }} · {{ $vehicle->id }}</p></div><button type="button" data-close-dialog>×</button></div><form method="POST" action="{{ route('admin.vehicles.update', $vehicle) }}" class="dialog-form">@csrf @method('PATCH')<div class="form-grid"><label><span>Brand</span><input name="brand" value="{{ $vehicle->brand }}" required></label><label><span>Model</span><input name="model" value="{{ $vehicle->model }}" required></label><label><span>Year</span><input name="year" type="number" value="{{ $vehicle->year }}" required></label><label><span>Mileage (km)</span><input name="mileage_km" type="number" min="0" value="{{ $vehicle->mileage_km }}" required></label><label><span>Health score</span><input name="health_score" type="number" min="0" max="100" value="{{ $vehicle->health_score }}" required></label><label><span>Nickname</span><input name="nickname" value="{{ $vehicle->nickname }}"></label><label class="full"><span>Plate number</span><input name="plate_number" value="{{ $vehicle->plate_number }}"></label></div><div class="dialog-actions"><button type="button" class="admin-button secondary" data-close-dialog>Cancel</button><button class="admin-button primary" type="submit">Save vehicle</button></div></form><div class="danger-zone"><div><strong>Delete vehicle</strong><p>Allowed only when no diagnostic analysis is active.</p></div><form method="POST" action="{{ route('admin.vehicles.destroy', $vehicle) }}">@csrf @method('DELETE')<button class="admin-button danger" type="submit" data-confirm="Delete this vehicle record?">Delete</button></form></div></dialog>@endforeach
            </section>

            <section class="admin-view" data-view="diagnostics">
                <x-admin-heading title="Diagnostics" eyebrow="AI DELIVERY" description="Inspect every analysis, input volume, report status, and operational error." />
                <div class="resource-stats"><article><span class="metric-icon blue">◎</span><div><small>Total sessions</small><strong>{{ number_format($overview['diagnostics']) }}</strong></div></article><article><span class="metric-icon cyan">✓</span><div><small>Completed shown</small><strong>{{ number_format($diagnostics->where('status', 'completed')->count()) }}</strong></div></article><article><span class="metric-icon amber">◌</span><div><small>In progress</small><strong>{{ number_format($diagnostics->whereIn('status', ['queued','analyzing','uploading'])->count()) }}</strong></div></article><article><span class="metric-icon red">!</span><div><small>Failed shown</small><strong>{{ number_format($diagnostics->where('status', 'failed')->count()) }}</strong></div></article></div>
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search session, driver, vehicle, or error…" data-table-search="diagnostics-table"></label><div class="toolbar-note">Latest 50 sessions</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="diagnostics-table" data-export-name="diagnostics"><thead><tr><th>Session</th><th>Driver & vehicle</th><th>Inputs</th><th>Report</th><th>Progress</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>
                    @forelse ($diagnostics as $diagnosis)<tr><td><strong>{{ Str::limit($diagnosis->id, 12, '…') }}</strong><small>{{ $diagnosis->current_step }}</small></td><td><strong>{{ $diagnosis->user?->name ?? 'Deleted user' }}</strong><small>{{ $diagnosis->vehicle?->brand }} {{ $diagnosis->vehicle?->model }} · {{ $diagnosis->vehicle?->year }}</small></td><td>{{ $diagnosis->media_count }} media · {{ $diagnosis->obd_snapshots_count }} OBD</td><td><strong>{{ $diagnosis->report?->translations?->firstWhere('locale', 'en')?->title ?? 'Not ready' }}</strong><small>{{ $diagnosis->error_code ?: ($diagnosis->description ? Str::limit($diagnosis->description, 45) : 'No text description') }}</small></td><td><b>{{ $diagnosis->progress_percentage }}%</b></td><td><span class="status-pill {{ $statusTone($diagnosis->status) }}">{{ $diagnosis->status }}</span></td><td>{{ $diagnosis->created_at?->diffForHumans() }}</td><td><button class="table-action" type="button" data-open-dialog="diagnosis-{{ $diagnosis->id }}">Inspect</button></td></tr>
                    @empty <tr><td colspan="8"><div class="empty-state">No diagnostics found.</div></td></tr> @endforelse
                </tbody></table></div></article>
                @foreach ($diagnostics as $diagnosis)<dialog class="admin-dialog" id="diagnosis-{{ $diagnosis->id }}"><div class="dialog-head"><div><span>Diagnostic session</span><h2>{{ $diagnosis->vehicle?->brand }} {{ $diagnosis->vehicle?->model }}</h2><p>{{ $diagnosis->id }}</p></div><button type="button" data-close-dialog>×</button></div><div class="detail-grid"><div><span>Status</span><strong>{{ $diagnosis->status }} · {{ $diagnosis->progress_percentage }}%</strong></div><div><span>Current step</span><strong>{{ $diagnosis->current_step }}</strong></div><div><span>Prompt</span><strong>{{ $diagnosis->prompt_version }}</strong></div><div><span>Market</span><strong>{{ $diagnosis->market_city ?: '—' }} · {{ $diagnosis->market_currency ?: '—' }}</strong></div></div>@if($diagnosis->safe_error_message)<div class="error-detail"><strong>{{ $diagnosis->error_code }}</strong><p>{{ $diagnosis->safe_error_message }}</p></div>@endif<div class="dialog-actions spread">@if(in_array($diagnosis->status, ['failed','cancelled'], true))<form method="POST" action="{{ route('admin.diagnostics.retry', $diagnosis) }}">@csrf<button class="admin-button primary" type="submit">Retry analysis</button></form>@endif @if(!in_array($diagnosis->status, ['completed','cancelled'], true))<form method="POST" action="{{ route('admin.diagnostics.cancel', $diagnosis) }}">@csrf<button class="admin-button secondary" type="submit" data-confirm="Cancel this diagnostic analysis?">Cancel run</button></form>@endif @if(in_array($diagnosis->status, ['draft','failed','cancelled'], true))<form method="POST" action="{{ route('admin.diagnostics.destroy', $diagnosis) }}">@csrf @method('DELETE')<button class="admin-button danger" type="submit" data-confirm="Permanently delete this diagnostic and its dependent data?">Delete</button></form>@endif</div></dialog>@endforeach
            </section>

            <section class="admin-view" data-view="mechanics">
                <div class="admin-heading compact-heading"><div><span class="admin-eyebrow"><i></i> WORKSHOP NETWORK</span><h1>Mechanics</h1><p>Create partners and control verification, contact details, location, and specialties.</p></div><button class="admin-button primary" type="button" data-open-dialog="mechanic-create">+ Add mechanic</button></div>
                <div class="resource-stats"><article><span class="metric-icon blue">⌘</span><div><small>Shown</small><strong>{{ number_format($mechanics->count()) }}</strong></div></article><article><span class="metric-icon cyan">✓</span><div><small>Verified</small><strong>{{ number_format($mechanics->where('verified', true)->count()) }}</strong></div></article><article><span class="metric-icon amber">◌</span><div><small>Pending review</small><strong>{{ number_format($mechanics->where('verified', false)->count()) }}</strong></div></article><article><span class="metric-icon purple">▦</span><div><small>Appointments</small><strong>{{ number_format($mechanics->sum('appointments_count')) }}</strong></div></article></div>
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search workshop, city, email, or specialty…" data-table-search="mechanics-table"></label><div class="toolbar-note">Latest 50 workshops</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="mechanics-table" data-export-name="mechanics"><thead><tr><th>Workshop</th><th>Location</th><th>Specialties</th><th>Rating</th><th>Bookings</th><th>Status</th><th></th></tr></thead><tbody>
                    @forelse ($mechanics as $mechanic)<tr><td><strong>{{ $mechanic->name_en }}</strong><small>{{ $mechanic->email ?: $mechanic->phone }}</small></td><td>{{ $mechanic->city }}, {{ $mechanic->country_code }}<small>{{ $mechanic->address }}</small></td><td>{{ $mechanic->specialties->pluck('name_en')->join(', ') ?: 'General service' }}</td><td>{{ number_format($mechanic->rating_average, 1) }} ★<small>{{ $mechanic->rating_count }} reviews</small></td><td>{{ $mechanic->appointments_count }}</td><td><span class="status-pill {{ $statusTone(!$mechanic->active ? 'suspended' : ($mechanic->verified ? 'verified' : 'pending')) }}">{{ !$mechanic->active ? 'disabled' : ($mechanic->verified ? 'verified' : 'pending') }}</span></td><td><button class="table-action" type="button" data-open-dialog="mechanic-{{ $mechanic->id }}">Manage</button></td></tr>
                    @empty <tr><td colspan="7"><div class="empty-state">No mechanics found.</div></td></tr> @endforelse
                </tbody></table></div></article>
                <dialog class="admin-dialog" id="mechanic-create"><div class="dialog-head"><div><span>Workshop network</span><h2>Add mechanic</h2><p>Create a new customer-facing workshop profile.</p></div><button type="button" data-close-dialog>×</button></div>@include('partials.admin-mechanic-form', ['mechanic' => null])</dialog>
                @foreach ($mechanics as $mechanic)<dialog class="admin-dialog" id="mechanic-{{ $mechanic->id }}"><div class="dialog-head"><div><span>Workshop profile</span><h2>{{ $mechanic->name_en }}</h2><p>{{ $mechanic->id }}</p></div><button type="button" data-close-dialog>×</button></div>@include('partials.admin-mechanic-form', ['mechanic' => $mechanic])</dialog>@endforeach
            </section>

            <section class="admin-view" data-view="appointments">
                <x-admin-heading title="Appointments" eyebrow="BOOKING OPERATIONS" description="Coordinate customer bookings and update workshop progress." />
                <div class="resource-stats"><article><span class="metric-icon blue">▦</span><div><small>Shown</small><strong>{{ number_format($appointments->count()) }}</strong></div></article><article><span class="metric-icon amber">◌</span><div><small>Requested</small><strong>{{ number_format($appointments->where('status', 'requested')->count()) }}</strong></div></article><article><span class="metric-icon cyan">✓</span><div><small>Confirmed</small><strong>{{ number_format($appointments->where('status', 'confirmed')->count()) }}</strong></div></article><article><span class="metric-icon purple">⌘</span><div><small>Completed</small><strong>{{ number_format($appointments->where('status', 'completed')->count()) }}</strong></div></article></div>
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search booking, driver, workshop, or vehicle…" data-table-search="appointments-table"></label><div class="toolbar-note">Latest 50 appointments</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="appointments-table" data-export-name="appointments"><thead><tr><th>Booking</th><th>Driver</th><th>Workshop</th><th>Vehicle</th><th>Schedule</th><th>Status</th><th></th></tr></thead><tbody>
                    @forelse ($appointments as $appointment)<tr><td><strong>{{ Str::limit($appointment->id, 12, '…') }}</strong><small>{{ $appointment->created_at?->diffForHumans() }}</small></td><td>{{ $appointment->user?->name ?? 'Deleted user' }}<small>{{ $appointment->user?->email }}</small></td><td>{{ $appointment->mechanic?->name_en }}</td><td>{{ $appointment->vehicle?->brand }} {{ $appointment->vehicle?->model }}<small>{{ $appointment->vehicle?->year }}</small></td><td><strong>{{ $appointment->requested_start_at?->format('M j, Y · H:i') }}</strong><small>{{ $appointment->requested_end_at?->diffInMinutes($appointment->requested_start_at) }} minutes</small></td><td><span class="status-pill {{ $statusTone($appointment->status) }}">{{ $appointment->status }}</span></td><td><button class="table-action" type="button" data-open-dialog="appointment-{{ $appointment->id }}">Manage</button></td></tr>
                    @empty <tr><td colspan="7"><div class="empty-state">No appointments found.</div></td></tr> @endforelse
                </tbody></table></div></article>
                @foreach ($appointments as $appointment)<dialog class="admin-dialog" id="appointment-{{ $appointment->id }}"><div class="dialog-head"><div><span>Booking management</span><h2>{{ $appointment->user?->name }} → {{ $appointment->mechanic?->name_en }}</h2><p>{{ $appointment->requested_start_at?->format('F j, Y · H:i') }}</p></div><button type="button" data-close-dialog>×</button></div><form class="dialog-form" method="POST" action="{{ route('admin.appointments.update', $appointment) }}">@csrf @method('PATCH')<div class="form-grid"><label class="full"><span>Status</span><select name="status">@foreach(['requested','confirmed','inProgress','completed','cancelled'] as $state)<option value="{{ $state }}" @selected($appointment->status === $state)>{{ ucfirst($state) }}</option>@endforeach</select></label><label class="full"><span>Mechanic note</span><textarea name="mechanic_note" rows="4">{{ $appointment->mechanic_note }}</textarea></label><label class="full"><span>Cancellation reason</span><textarea name="cancellation_reason" rows="3">{{ $appointment->cancellation_reason }}</textarea></label></div><div class="dialog-actions"><button type="button" class="admin-button secondary" data-close-dialog>Cancel</button><button class="admin-button primary" type="submit">Save appointment</button></div></form></dialog>@endforeach
            </section>

            <section class="admin-view" data-view="billing">
                <x-admin-heading title="Billing" eyebrow="STORE & ENTITLEMENTS" description="Manage plan availability, store products, transactions, and billing events." />
                <div class="resource-stats"><article><span class="metric-icon blue">¤</span><div><small>Active subscriptions</small><strong>{{ number_format($billingOverview['activeSubscriptions']) }}</strong></div></article><article><span class="metric-icon amber">◌</span><div><small>Grace / retry</small><strong>{{ number_format($billingOverview['graceOrRetry']) }}</strong></div></article><article><span class="metric-icon cyan">▤</span><div><small>Credits outstanding</small><strong>{{ number_format($billingOverview['creditsOutstanding']) }}</strong></div></article><article><span class="metric-icon red">!</span><div><small>Events needing attention</small><strong>{{ number_format($billingOverview['eventsNeedingAttention']) }}</strong></div></article></div>
                <div class="stacked-panels">
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Billing plans</strong><span>Limits and storefront visibility</span></div><span class="environment-pill">{{ strtoupper(config('billing.environment')) }}</span></div><div class="admin-table-wrap"><table class="admin-table resource-table" data-export-name="billing-plans"><thead><tr><th>Plan</th><th>Type</th><th>Max vehicles</th><th>Reports / period</th><th>Flags</th><th>Save</th></tr></thead><tbody>@forelse($billingPlans as $plan)<tr><td><strong>{{ $plan->localizations->firstWhere('locale','en')?->name ?? $plan->code }}</strong><small>{{ $plan->code }}</small></td><td>{{ $plan->type }}</td><td colspan="4"><form class="inline-editor" method="POST" action="{{ route('admin.billing.plans.update', $plan) }}">@csrf @method('PATCH')<input type="number" name="maxVehicles" min="1" value="{{ $plan->max_vehicles }}"><input type="number" name="reportsPerPeriod" min="1" value="{{ $plan->reports_per_period }}"><label><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($plan->active)>Active</label><label><input type="hidden" name="published" value="0"><input type="checkbox" name="published" value="1" @checked($plan->published)>Published</label><label><input type="hidden" name="recommended" value="0"><input type="checkbox" name="recommended" value="1" @checked($plan->recommended)>Featured</label><button class="table-action" type="submit">Save</button></form></td></tr>@empty<tr><td colspan="6"><div class="empty-state">Billing schema is ready, but no plans exist.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Store products</strong><span>Provider state and sale availability</span></div></div><div class="admin-table-wrap"><table class="admin-table resource-table" data-export-name="store-products"><thead><tr><th>Platform</th><th>Product</th><th>Plan</th><th>Environment</th><th>State</th><th>Sale</th><th></th></tr></thead><tbody>@forelse($billingProducts as $product)<tr><td>{{ ucfirst($product->platform) }}</td><td><strong>{{ $product->product_id }}</strong></td><td>{{ $product->plan?->code }}</td><td>{{ $product->environment }}</td><td colspan="3"><form class="inline-editor" method="POST" action="{{ route('admin.billing.products.update', $product) }}">@csrf @method('PATCH')<select name="storeStatus">@foreach(['pending','active','rejected','retired'] as $state)<option value="{{ $state }}" @selected($product->store_status === $state)>{{ ucfirst($state) }}</option>@endforeach</select><label><input type="hidden" name="activeForSale" value="0"><input type="checkbox" name="activeForSale" value="1" @checked($product->active_for_sale)>Active for sale</label><button class="table-action" type="submit">Save</button></form></td></tr>@empty<tr><td colspan="7"><div class="empty-state">No store products configured.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Recent transactions</strong><span>Latest verified store purchases</span></div></div><div class="admin-table-wrap"><table class="admin-table resource-table" data-export-name="transactions"><thead><tr><th>User</th><th>Platform</th><th>Product</th><th>State</th><th>Purchased</th><th>Verified</th></tr></thead><tbody>@forelse($billingTransactions as $purchase)<tr><td>{{ $purchase->user?->email ?? 'Deleted user' }}</td><td>{{ $purchase->platform }}</td><td>{{ $purchase->storeProduct?->product_id ?? $purchase->product_id }}</td><td><span class="status-pill {{ $statusTone($purchase->purchase_state) }}">{{ $purchase->purchase_state }}</span></td><td>{{ $purchase->purchased_at?->format('M j, Y H:i') }}</td><td>{{ $purchase->last_verified_at?->diffForHumans() ?? '—' }}</td></tr>@empty<tr><td colspan="6"><div class="empty-state">No transactions yet.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Billing events</strong><span>Webhook processing and recovery</span></div></div><div class="admin-table-wrap"><table class="admin-table resource-table" data-export-name="billing-events"><thead><tr><th>Provider</th><th>Event</th><th>Status</th><th>Attempts</th><th>Error</th><th>Received</th><th></th></tr></thead><tbody>@forelse($billingEvents as $event)<tr><td>{{ ucfirst($event->provider) }}</td><td><strong>{{ $event->event_type }}</strong><small>{{ Str::limit($event->provider_event_id, 24) }}</small></td><td><span class="status-pill {{ $statusTone($event->processing_status) }}">{{ $event->processing_status }}</span></td><td>{{ $event->attempts }}</td><td>{{ Str::limit($event->error_message, 55) ?: '—' }}</td><td>{{ $event->received_at?->diffForHumans() }}</td><td>@unless(in_array($event->processing_status,['processed','ignored'],true))<form method="POST" action="{{ route('admin.billing.events.reprocess', $event) }}">@csrf<button class="table-action" type="submit">Reprocess</button></form>@endunless</td></tr>@empty<tr><td colspan="7"><div class="empty-state">No billing events received.</div></td></tr>@endforelse</tbody></table></div></article>
                </div>
            </section>

            <section class="admin-view" data-view="ai">
                <x-admin-heading title="AI operations" eyebrow="MODEL RELIABILITY" description="Monitor model selection, latency, token use, provider cost, and failure details." />
                <div class="resource-stats"><article><span class="metric-icon blue">✦</span><div><small>Runs shown</small><strong>{{ number_format($aiRuns->count()) }}</strong></div></article><article><span class="metric-icon cyan">✓</span><div><small>Completed</small><strong>{{ number_format($aiRuns->where('status','completed')->count()) }}</strong></div></article><article><span class="metric-icon amber">◌</span><div><small>In progress</small><strong>{{ number_format($aiRuns->whereIn('status',['queued','running'])->count()) }}</strong></div></article><article><span class="metric-icon red">!</span><div><small>Failed</small><strong>{{ number_format($aiRuns->where('status','failed')->count()) }}</strong></div></article></div>
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search run, task, model, or error…" data-table-search="ai-table"></label><div class="toolbar-note">Latest 50 model runs</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="ai-table" data-export-name="ai-runs"><thead><tr><th>Run</th><th>Task & model</th><th>Customer</th><th>Latency</th><th>Tokens</th><th>Cost</th><th>Status</th><th></th></tr></thead><tbody>@forelse($aiRuns as $run)<tr><td><strong>{{ Str::limit($run->id, 12, '…') }}</strong><small>Attempt {{ $run->attempt }}</small></td><td><strong>{{ $run->task_type }}</strong><small>{{ $run->provider }} · {{ $run->model }}</small></td><td>{{ $run->session?->user?->name ?? 'Unknown' }}</td><td>{{ $run->latency_milliseconds ? number_format($run->latency_milliseconds).' ms' : '—' }}</td><td>{{ number_format(($run->input_token_count ?? 0) + ($run->output_token_count ?? 0)) }}</td><td>{{ $run->estimated_provider_cost !== null ? ($run->cost_currency ?: 'USD').' '.number_format($run->estimated_provider_cost, 4) : '—' }}</td><td><span class="status-pill {{ $statusTone($run->status) }}">{{ $run->status }}</span>@if($run->safe_error_message)<small title="{{ $run->safe_error_message }}">{{ Str::limit($run->safe_error_category ?: $run->safe_error_message, 35) }}</small>@endif</td><td>@if($run->status === 'failed')<form method="POST" action="{{ route('admin.ai-runs.retry', $run) }}">@csrf<button class="table-action" type="submit">Retry</button></form>@endif</td></tr>@empty<tr><td colspan="8"><div class="empty-state">No AI runs yet.</div></td></tr>@endforelse</tbody></table></div></article>
            </section>

            <section class="admin-view" data-view="notifications">
                <div class="admin-heading compact-heading"><div><span class="admin-eyebrow"><i></i> CUSTOMER COMMUNICATION</span><h1>Notifications</h1><p>Create bilingual broadcasts and inspect messages delivered to customer inboxes.</p></div><button class="admin-button primary" type="button" data-open-dialog="broadcast-create">+ New broadcast</button></div>
                <div class="resource-stats"><article><span class="metric-icon blue">♢</span><div><small>Total shown</small><strong>{{ number_format($notifications->count()) }}</strong></div></article><article><span class="metric-icon cyan">✓</span><div><small>Sent</small><strong>{{ number_format($notifications->whereNotNull('sent_at')->count()) }}</strong></div></article><article><span class="metric-icon purple">◉</span><div><small>Read</small><strong>{{ number_format($notifications->whereNotNull('read_at')->count()) }}</strong></div></article><article><span class="metric-icon amber">◌</span><div><small>Unread</small><strong>{{ number_format($notifications->whereNull('read_at')->count()) }}</strong></div></article></div>
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search user, type, or message…" data-table-search="notifications-table"></label><div class="toolbar-note">Latest 50 notifications</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="notifications-table" data-export-name="notifications"><thead><tr><th>Recipient</th><th>Type</th><th>English message</th><th>Arabic message</th><th>Delivery</th><th>Created</th></tr></thead><tbody>@forelse($notifications as $notification)<tr><td>{{ $notification->user?->name ?? 'Deleted user' }}<small>{{ $notification->user?->email }}</small></td><td>{{ $notification->type }}</td><td><strong>{{ $notification->title_en }}</strong><small>{{ Str::limit($notification->body_en, 65) }}</small></td><td dir="rtl"><strong>{{ $notification->title_ar }}</strong><small>{{ Str::limit($notification->body_ar, 65) }}</small></td><td><span class="status-pill {{ $notification->read_at ? 'success' : 'neutral' }}">{{ $notification->read_at ? 'read' : ($notification->sent_at ? 'sent' : 'queued') }}</span></td><td>{{ $notification->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="6"><div class="empty-state">No notifications yet.</div></td></tr>@endforelse</tbody></table></div></article>
                <dialog class="admin-dialog" id="broadcast-create"><div class="dialog-head"><div><span>Customer communication</span><h2>New broadcast</h2><p>A bilingual notification is stored for every selected recipient.</p></div><button type="button" data-close-dialog>×</button></div><form class="dialog-form" method="POST" action="{{ route('admin.notifications.broadcast') }}">@csrf<div class="form-grid"><label><span>Audience</span><select name="audience" data-audience-select><option value="active">All active users</option><option value="all">All users</option><option value="user">One user</option></select></label><label data-audience-user hidden><span>User</span><select name="user_id"><option value="">Select user</option>@foreach($users->whereNull('deleted_at') as $user)<option value="{{ $user->id }}">{{ $user->name }} — {{ $user->email }}</option>@endforeach</select></label><label class="full"><span>English title</span><input name="title_en" maxlength="160" required></label><label class="full"><span>English message</span><textarea name="body_en" rows="3" maxlength="1000" required></textarea></label><label class="full"><span>Arabic title</span><input name="title_ar" dir="rtl" maxlength="160" required></label><label class="full"><span>Arabic message</span><textarea name="body_ar" dir="rtl" rows="3" maxlength="1000" required></textarea></label></div><div class="dialog-actions"><button type="button" class="admin-button secondary" data-close-dialog>Cancel</button><button class="admin-button primary" type="submit" data-confirm="Create this broadcast for the selected audience?">Create broadcast</button></div></form></dialog>
            </section>

            <section class="admin-view" data-view="catalog">
                <div class="admin-heading compact-heading"><div><span class="admin-eyebrow"><i></i> REFERENCE DATA</span><h1>Catalog & rates</h1><p>Control vehicle brands and models, maintenance definitions, currency rates, and regional labor sources.</p></div><div class="heading-actions"><button class="admin-button secondary" type="button" data-open-dialog="model-create">+ Vehicle model</button><button class="admin-button primary" type="button" data-open-dialog="make-create">+ Vehicle make</button></div></div>
                <div class="catalog-grid">
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Vehicle makes</strong><span>{{ number_format($vehicleMakes->count()) }} makes in the customer catalog</span></div></div><div class="admin-table-wrap compact-scroll"><table class="admin-table resource-table"><thead><tr><th>Make</th><th>Code</th><th>Models</th><th>Status</th><th></th></tr></thead><tbody>@forelse($vehicleMakes as $make)<tr><td><strong>{{ $make->name_en }}</strong><small dir="rtl">{{ $make->name_ar }}</small></td><td>{{ $make->code }}</td><td>{{ $make->models_count }}</td><td><span class="status-pill {{ $make->active ? 'success' : 'neutral' }}">{{ $make->active ? 'active' : 'disabled' }}</span></td><td><button class="table-action" type="button" data-open-dialog="make-{{ $make->id }}">Edit</button></td></tr>@empty<tr><td colspan="5"><div class="empty-state">No vehicle makes.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Vehicle models</strong><span>{{ number_format($vehicleModels->count()) }} models shown</span></div><button class="table-action" type="button" data-open-dialog="model-create">+ Add</button></div><div class="admin-table-wrap compact-scroll"><table class="admin-table resource-table"><thead><tr><th>Model</th><th>Make</th><th>Years</th><th>Status</th><th></th></tr></thead><tbody>@forelse($vehicleModels as $model)<tr><td><strong>{{ $model->name_en }}</strong><small>{{ $model->code }} · {{ $model->name_ar }}</small></td><td>{{ $model->make?->name_en }}</td><td>{{ $model->start_year ?: 'Any' }}–{{ $model->end_year ?: 'Now' }}</td><td><span class="status-pill {{ $model->active ? 'success' : 'neutral' }}">{{ $model->active ? 'active' : 'disabled' }}</span></td><td><button class="table-action" type="button" data-open-dialog="model-{{ $model->id }}">Edit</button></td></tr>@empty<tr><td colspan="5"><div class="empty-state">No vehicle models.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Maintenance services</strong><span>Intervals used for reminders</span></div><button class="table-action" type="button" data-open-dialog="service-create">+ Add</button></div><div class="admin-table-wrap compact-scroll"><table class="admin-table resource-table"><thead><tr><th>Service</th><th>Months</th><th>Kilometers</th><th>Status</th><th></th></tr></thead><tbody>@forelse($maintenanceServices as $service)<tr><td><strong>{{ $service->name_en }}</strong><small>{{ $service->code }}</small></td><td>{{ $service->default_month_interval ?: '—' }}</td><td>{{ $service->default_km_interval ? number_format($service->default_km_interval) : '—' }}</td><td><span class="status-pill {{ $service->active ? 'success' : 'neutral' }}">{{ $service->active ? 'active' : 'disabled' }}</span></td><td><button class="table-action" type="button" data-open-dialog="service-{{ $service->id }}">Edit</button></td></tr>@empty<tr><td colspan="5"><div class="empty-state">No maintenance services.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Currency rates</strong><span>Latest 30 conversion sources</span></div><button class="table-action" type="button" data-open-dialog="currency-create">+ Add</button></div><div class="admin-table-wrap compact-scroll"><table class="admin-table resource-table"><thead><tr><th>Pair</th><th>Rate</th><th>Provider</th><th>Effective</th></tr></thead><tbody>@forelse($currencyRates as $rate)<tr><td><strong>{{ $rate->base_currency }} / {{ $rate->quote_currency }}</strong></td><td>{{ $rate->rate }}</td><td>{{ $rate->provider }}</td><td>{{ $rate->effective_at?->format('M j, Y H:i') }}</td></tr>@empty<tr><td colspan="4"><div class="empty-state">No currency rates.</div></td></tr>@endforelse</tbody></table></div></article>
                    <article class="admin-panel resource-table-panel"><div class="panel-title"><div><strong>Labor rates</strong><span>Latest 30 regional sources</span></div><button class="table-action" type="button" data-open-dialog="labor-create">+ Add</button></div><div class="admin-table-wrap compact-scroll"><table class="admin-table resource-table"><thead><tr><th>Market</th><th>Category</th><th>Hourly range</th><th>Observed</th></tr></thead><tbody>@forelse($laborRates as $rate)<tr><td><strong>{{ $rate->city ?: 'All cities' }}, {{ $rate->country_code }}</strong></td><td>{{ $rate->service_category }}</td><td>{{ $rate->currency }} {{ $rate->hourly_low }}–{{ $rate->hourly_high }}</td><td>{{ $rate->observed_at?->format('M j, Y') }}</td></tr>@empty<tr><td colspan="4"><div class="empty-state">No labor rates.</div></td></tr>@endforelse</tbody></table></div></article>
                </div>
                @include('partials.admin-catalog-dialogs')
            </section>

            <section class="admin-view" data-view="settings">
                <x-admin-heading title="Settings" eyebrow="PLATFORM CONTROL" description="Control customer access, core features, localization defaults, and support details." />
                <form method="POST" action="{{ route('admin.settings.update') }}" class="settings-layout">@csrf @method('PATCH')
                    <div class="settings-main">
                        @foreach(collect($platformSettings)->groupBy('group', true) as $group => $groupSettings)<article class="admin-panel settings-panel"><div class="panel-title"><div><strong>{{ $group }}</strong><span>{{ $groupSettings->count() }} platform controls</span></div></div><div class="settings-list">@foreach($groupSettings as $key => $setting)
                            @if($setting['type'] === 'boolean')<label class="setting-row"><span><strong>{{ $setting['label'] }}</strong><small>{{ $setting['description'] }}</small></span><span class="toggle"><input type="hidden" name="settings[{{ $key }}]" value="0"><input type="checkbox" name="settings[{{ $key }}]" value="1" @checked((bool)$setting['value'])><i></i></span></label>
                            @else<label class="setting-row field"><span><strong>{{ $setting['label'] }}</strong><small>{{ $setting['description'] }}</small></span>@if($setting['type'] === 'locale')<select name="settings[{{ $key }}]"><option value="en" @selected($setting['value']==='en')>English</option><option value="ar" @selected($setting['value']==='ar')>Arabic</option></select>@else<input name="settings[{{ $key }}]" type="{{ $setting['type'] === 'email' ? 'email' : 'text' }}" value="{{ $setting['value'] }}" maxlength="{{ $setting['type'] === 'text' ? 500 : ($setting['type'] === 'country' ? 2 : ($setting['type'] === 'currency' ? 3 : 255)) }}" @required($key !== 'maintenance_banner')>@endif</label>@endif
                        @endforeach</div></article>@endforeach
                        <div class="sticky-save"><div><strong>Platform configuration</strong><small>Changes become active for new API requests immediately.</small></div><button class="admin-button primary" type="submit" @disabled(! $databaseControlsAvailable)>Save settings</button></div>
                    </div>
                    <aside class="admin-panel inventory-panel"><div class="panel-title"><div><strong>Data inventory</strong><span>Live row totals by domain</span></div></div><div class="inventory-list">@foreach($dataInventory as $label => $count)<div><span>{{ $label }}</span><strong>{{ number_format($count) }}</strong></div>@endforeach</div></aside>
                </form>
            </section>

            <section class="admin-view" data-view="audit">
                <x-admin-heading title="Audit trail" eyebrow="ACCOUNTABILITY" description="Review sensitive administrative and system actions with request correlation." />
                <article class="admin-panel resource-table-panel"><div class="resource-toolbar"><label><span>⌕</span><input type="search" placeholder="Search action, target, request, or administrator…" data-table-search="audit-table"></label><div class="toolbar-note">Latest 75 events</div></div><div class="admin-table-wrap"><table class="admin-table resource-table" id="audit-table" data-export-name="audit-log"><thead><tr><th>Action</th><th>Target</th><th>Administrator / actor</th><th>Request ID</th><th>Created</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td><strong>{{ $log->action }}</strong></td><td>{{ class_basename($log->target_type ?: 'System') }}<small>{{ $log->target_id ?: '—' }}</small></td><td>{{ data_get($log->metadata_json, 'administrator') ?: ($log->actor_user_id ?: 'System') }}</td><td><code>{{ $log->request_id }}</code></td><td>{{ $log->created_at?->format('M j, Y H:i:s') }}<small>{{ $log->created_at?->diffForHumans() }}</small></td></tr>@empty<tr><td colspan="5"><div class="empty-state">No audit events yet.</div></td></tr>@endforelse</tbody></table></div></article>
            </section>
        </main>
    </div>
    <div class="admin-overlay" data-admin-overlay></div>
</body>
</html>
